### ISSUE TITLE
can't run the server

### ISSUE THREAD

**Issue by dimashiii** [akshatgarg12/The-Office#4]
why does this command is not working?

npm run dev 
<img width="938" alt="Screenshot 2021-08-25 at 8 33 14 PM" src="https://user-images.githubusercontent.com/79325373/130815520-ca4272ee-76d1-4062-9af0-a173e461ad4d.png">

or node server.js
<img width="950" alt="Screenshot 2021-08-25 at 8 31 46 PM" src="https://user-images.githubusercontent.com/79325373/130815231-64336fe2-54df-4bc3-82d0-b82fc21ef2a7.png">

client works properly

**Comment by akshatgarg12** [comment]
Hey @dimashiii , to run the server you will have to create a file '.env' using the template 'sample.env' which I have provided in the server folder. These enviornment variables are required by the server to work.
